name: rss-mailer

on:
  schedule:
    - cron: "*/5 * * * *"   # 5분마다 실행
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      # ✅ 중복 방지를 위한 state(상태) 폴더 캐시 복원
      - name: Restore state cache
        uses: actions/cache@v4
        with:
          path: .state
          key: rss-state-${{ github.ref }}
          restore-keys: rss-state-

      # ✅ Secrets를 코드에서 쓰는 환경변수로 주입
      - name: Run digest
        env:
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          MAIL_TO: ${{ secrets.MAIL_TO }}
        run: python rss_digest.py
